
import "./globals.css";
import App from "@/components/NavBar";
import SideNavBar from "@/components/SideNavBar";
import { Toaster } from "react-hot-toast";
import UserProvider from "@/context/UserProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Toaster />
          <App />
          <div className="flex h-screen">
            <SideNavBar />
            <main className="flex-1 overflow-auto">{children}</main>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
